image: node:24-slim

stages:
  - install
  - test

cache:
  paths:
    - node_modules/

variables:
  NODE_ENV: test

before_script:
  - npm ci

install:
  stage: install
  script:
    - echo "Dependencies installed"

test:
  stage: test
  script:
    - npm test
