image: node:20-slim

stages:
  - install
  - test

cache:
  paths:
    - node_modules/

variables:
  NODE_ENV: test
  MONGO_URI: "mongodb+srv://${MONGO_USER}:${MONGO_PASS}@${MONGO_HOST}/${MONGO_DB}?retryWrites=true&w=majority"

before_script:
  - npm ci

install:
  stage: install
  script:
    - echo "Dependencies installed"

test:
  stage: test
  script:
    - npm test
