stages:
  - install
  - test
  - build
  - docker

install:
  stage: install
  script:
    - npm install

test:
  stage: test
  script:
    - npm run lint
    - npm run test

build:
  stage: build
  script:
    - npm run build

docker:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t registry.gitlab.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest .
    - docker push registry.gitlab.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest
  only:
    - main
